version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: my_postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: documents-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - my-db-data:/var/lib/postgresql/data

volumes:
  my-db-data:
    driver: local